-- begin SHOP_SALES_ORDER
alter table SHOP_SALES_ORDER add constraint FK_SHOP_SALES_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references SHOP_CUSTOMER(ID)^
create index IDX_SHOP_SALES_ORDER_ON_CUSTOMER on SHOP_SALES_ORDER (CUSTOMER_ID)^
-- end SHOP_SALES_ORDER
-- begin SHOP_CUSTOMER
create unique index IDX_SHOP_CUSTOMER_UNIQ_EMAIL on SHOP_CUSTOMER (EMAIL)^
-- end SHOP_CUSTOMER
-- begin SHOP_ORDER_POSITION
alter table SHOP_ORDER_POSITION add constraint FK_SHOP_ORDER_POSITION_ON_PRODUCT foreign key (PRODUCT_ID) references SHOP_PRODUCT(ID)^
alter table SHOP_ORDER_POSITION add constraint FK_SHOP_ORDER_POSITION_ON_SALES_ORDER foreign key (SALES_ORDER_ID) references SHOP_SALES_ORDER(ID)^
create index IDX_SHOP_ORDER_POSITION_ON_PRODUCT on SHOP_ORDER_POSITION (PRODUCT_ID)^
create index IDX_SHOP_ORDER_POSITION_ON_SALES_ORDER on SHOP_ORDER_POSITION (SALES_ORDER_ID)^
-- end SHOP_ORDER_POSITION
